# Generated by Django 3.1.2 on 2020-11-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_banned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='The email address associated to this user.', max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
