# Generated by Django 3.1.4 on 2021-01-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201208_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non Binary'), ('X', 'Prefer Not To Say')], default='X', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Banned Status'),
        ),
    ]
