# Generated by Django 3.1.4 on 2021-03-22 02:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210322_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('status', models.CharField(choices=[('S', 'Sent'), ('A', 'Accepted')], default='S', max_length=1, verbose_name='Status')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='accounts.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Relationship',
                'verbose_name_plural': 'Relationships',
                'db_table': 'accounts-relationship',
                'ordering': ['created'],
            },
        ),
    ]
