# Generated by Django 3.1.4 on 2021-04-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210331_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('S', 'Sent'), ('R', 'Rejected'), ('V', 'Viewed')], default='S', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('sender', 'receiver')},
        ),
    ]
