# Generated by Django 3.1.7 on 2021-04-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210402_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blocks',
            field=models.ManyToManyField(blank=True, related_name='_profile_blocks_+', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_profile_friends_+', to='accounts.Profile'),
        ),
    ]
